# PowerShell script to build an executable for the BluPOS backend application using PyInstaller

# Path to the Python script you want to convert into an executable
# Adjust the path as necessary
$scriptPath = "BluPOS_Backend.py"

# Output folder for the executable
$outputFolder = "dist"

# Make sure PyInstaller is installed
try {
    Import-Module PyInstaller -ErrorAction Stop
} catch {
    Write-Host "PyInstaller is not installed. Please install it using pip: pip install pyinstaller"
    exit 1
}

# Change to the directory containing the Python script
Set-Location (Split-Path $scriptPath)

# Run PyInstaller to build the executable
# -F for a single executable
# -w to disable the console window (for GUI applications)
# Adjust the flags based on the specific needs of the application
pyinstaller -F -w $scriptPath

# Move the executable to the specified output folder
# Ensure that the output folder exists
if (-Not (Test-Path $outputFolder)) {
    New-Item -ItemType Directory -Path $outputFolder
}

# Move the built executable to the output folder
Move-Item -Path "dist\\*" -Destination "$outputFolder" -Force

# Clean up temporary files generated by PyInstaller
Remove-Item -Recurse -Force "build"  
Remove-Item -Force "dist\\$scriptPath"

# Inform the user that the build process is complete
Write-Host "Build completed! Executable is located in the '$outputFolder' folder."